version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: user
      POSTGRES_DB: todosDB
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/10-init.sql
    ports:
      - "5432:5432"
  web:
    build: .
    ports:
      - "3000:8000"
    depends_on:
      - db
